[package]
name = "m-task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mtask"
path = "src/main.rs"

[dependencies]
color-eyre = "0.5.11"
structopt = "0.3.25"
